# Inference config

# Emphasis on larger structures in scoring
quality.beta=3.0

# Weight of inferred structures
quality.alpha=1.0

# Minimum confidence to include an inference
inference.confidence.threshold=0.0